###############################################################################

DEVICE_BUILD_TOOL = gcc
DEVICE_BUILD_OBJCOPY = objcopy
PROJECT_SRC_FILES += $(wildcard $(ROOT)/src/drivers/posix_common/*.c)
ARCH_FLAGS += -std=gnu11

###############################################################################
