###############################################################################

BOARD_TYPE = naze32_rev6

###############################################################################

include makefiles/makefile.naze32_common

# Naze32 rev5 specific drivers
PROJECT_SRC_FILES += $(wildcard src/drivers/naze32_rev6/*.c)

###############################################################################

naze32_rev6: $(TARGET_IMG)

