###############################################################################

DEVICE_BUILD_TOOL = gcc
DEVICE_BUILD_OBJCOPY = objcopy
TARGET_BUILD_ID = elf

###############################################################################

# POSIX specific drivers
PROJECT_SRC_FILES += $(wildcard src/drivers/posix/*.c)

ARCH_FLAGS += -std=gnu11
